name = "newleaf"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./public"

[dev]
port = 8787
local_protocol = "http"

[build]
command = "npm run build"

[env.development]
vars = { ENVIRONMENT = "development" } 